### ISSUE TITLE
Include file with only macro collection declarations

### ISSUE THREAD

**Issue by astrorafael** [LeoVen/C-Macro-Collections#18]
# Feature Request Template

### What is the nature of this request?

* Restructure the main library include file to selective include only what you need

### Is your feature request related to a problem? Please describe.

Trying to use this library in a 32bit Cortex M0 microcontroller. Including macro_collections.h is overkill and gives compile error for stuff that I don't even need (multithreading, etc.)

### Describe the solution you'd like

I have produced a simple header file - for instance, macro_defs.h -  where only the global macros are defined. Then it is just a matter of including the needed header files in your code, like:

#include "cmc_list.h"
#include "ext_cmc_list.h"
#include "utl_futils.h"
#include "macro_defs.h"

The existing macro_collections.h can include this file as the very last and we have the same functionality as before

```

**Comment by astrorafael** [comment]
Amazing library, by the way ...

**Comment by LeoVen** [comment]
Thank you for this. I've been wanting to get back to this library for a while now. I'll see what I can do.
