### ISSUE TITLE
If PFX not set, assume PFX=SNAME

### ISSUE THREAD

**Issue by duarm** [LeoVen/C-Macro-Collections#39]
# Feature Request Template

### What is the nature of this request?

* New functionalities

### Is your feature request related to a problem? Please describe.

I think SNAME, the name of the collection, is a reasonable PFX. So maybe if PFX is not set, we could assume SNAME=PFX?

### Describe the solution you'd like

```c
#ifndef PFX
#define PFX SNAME
#endif // PFX
```

**Comment by LeoVen** [comment]
I think it would be best to have these paramaters set explicitly by the user

**Comment by duarm** [comment]
Fair enough, feel free to close
