### ISSUE TITLE
Define deallocator functions once in "new" functions

### ISSUE THREAD

**Issue by pfeatherstone** [LeoVen/C-Macro-Collections#8]
Can I suggest we parse the deallocator to the "new" function and hold it in the container, thus avoiding having to parse it to every "pop", "remove" and "clear" function.

**Comment by pfeatherstone** [comment]
Actually, we could even parse the deallocator to the CMC_GENERATE definition.

**Comment by LeoVen** [comment]
Hello, thanks for the suggestion. I've been considering this for a very long time already. I was thinking about a struct that contains all the necessary functions like free, compare, hash, etc. I've done something like it in [here](https://github.com/LeoVen/C-DataStructures-Library/blob/master/C-DataStructures-Library/interface/Interface.h). This could make the parameters list smaller and add more functionalities.

**Comment by LeoVen** [comment]
This has been already implemented in the dev branch. When the 1.8 release is done I'll merge it to master
