### ISSUE TITLE
list.h -  a couple of issues

### ISSUE THREAD

**Issue by pfeatherstone** [LeoVen/C-Macro-Collections#9]
Line 299, I think it should be
memmove(_list_->buffer, _list_->buffer + 1, **(_list_->count -  1)** * sizeof(V)); 

Line 311, I think it should be
memmove(_list_->buffer + index, _list_->buffer + index + 1, **(_list_->count - index - 1)** * sizeof(V));

I also suggest calling PFX##_pop_at(_list_, 0) inside PFX##_pop_front.
Also, all of the pop functions should be calling deallocators

**Comment by pfeatherstone** [comment]
How about this:

bool PFX##_pop_range(struct SNAME *_list_, size_t beg, size_t end)                       \
    {                                                                                        \
        if (PFX##_empty(_list_) || beg > end || end > _list_->count)                         \
            return false;                                                                    \
                                                                                             \
        if (_list_->deallocator)                                                             \
        {                                                                                    \
            size_t i = beg;                                                                  \
            for (; i < end ; i++)                                                            \
                _list_->deallocator(_list_->buffer[i]);                                      \
        }                                                                                    \
                                                                                             \
        size_t length = end - beg;                                                           \
        size_t remain = _list_->count - end;                                                 \
        if (remain > 0)                                                                      \
            memmove(&_list_->buffer[beg], &_list_->buffer[end], remain * sizeof(V));         \
        _list_->count -= length;                                                             \
        memset(&_list_->buffer[_list_->count], 0, length * sizeof(V));                       \
                                                                                             \
        return true;                                                                         \
    }                                                                                        \
                                                                                             \
    bool PFX##_pop_at(struct SNAME *_list_, size_t i)                                        \
    {                                                                                        \
        return PFX##_pop_range(_list_, i, i + 1);                                            \
    }                                                                                        \
                                                                                             \
    bool PFX##_pop_front(struct SNAME *_list_)                                               \
    {                                                                                        \
        return PFX##_pop_at(_list_, 0);                                                      \
    }                                                                                        \
                                                                                             \
    bool PFX##_pop_back(struct SNAME *_list_)                                                \
    {                                                                                        \
        return PFX##_pop_at(_list_, _list_->count - 1);                                      \
    }                                                                                        \
                                                                                             \
    void PFX##_pop_if(struct SNAME *_list_, bool (*condition)(V))                            \
    {                                                                                        \
        int* indices = malloc(_list_->count * sizeof(int));                                  \
        int i;                                                                               \
        for (i = _list_->count - 1; i >= 0 ; --i)                                            \
            indices[i] = condition(_list_->buffer[i]) ? i : -1;                              \
                                                                                             \
        for (i = _list_->count - 1; i >= 0 ; --i)                                            \
        {                                                                                    \
            if (indices[i] != -1)                                                            \
                PFX##_pop_at(_list_, indices[i]);                                            \
        }                                                                                    \
        free(indices);                                                                       \
    }                                                                                        \

**Comment by pfeatherstone** [comment]
In the last post I’ve realised that I don’t need to preallocate indices. I don’t know what I was thinking

**Comment by LeoVen** [comment]
Hi thank you for the suggestion. The indices are indeed wrong. I will get them fixed in the next release.

Regarding calling `PFX##_pop_at(list, 0)` inside `PFX##_pop_front` won't happen because I have another utility to this library cooking up. You will be able to set callback functions for each of the main functions of each collection. This means that if you set a callback function to `PFX##_pop_at` it will activate when `PFX##_pop_front` is called too. This, of course, could change.

Regarding deallocating the elements when it is popped: this was a design decision. What if the element being popped in a list is also handled by another list? O maybe another collection? So to get it freed from memory you will have to first access it with `PFX##_get` and then deallocate it.

**Comment by LeoVen** [comment]
This has been already fixed in the dev branch by b2bef4e
